/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppClaimsRouteImport } from './routes/_app.claims'
import { Route as AppCommandCenterRouteImport } from './routes/_app.command-center'
import { Route as AppConnectorsRouteImport } from './routes/_app.connectors'
import { Route as AppContractsRouteImport } from './routes/_app.contracts'
import { Route as AppCoreRouteImport } from './routes/_app.core'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDecisionsRouteImport } from './routes/_app.decisions'
import { Route as AppEnvironmentsRouteImport } from './routes/_app.environments'
import { Route as AppEvidenceRouteImport } from './routes/_app.evidence'
import { Route as AppGovernanceRouteImport } from './routes/_app.governance'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppSecretsRouteImport } from './routes/_app.secrets'
import { Route as AppSsoRouteImport } from './routes/_app.sso'
import { Route as AppTelemetryRouteImport } from './routes/_app.telemetry'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app.workflows.$workflowId'
import { Route as AppWorkflowsWorkflowIdRunsRouteImport } from './routes/_app.workflows.$workflowId.runs'
import { Route as AppWorkflowsRunsRunIdRouteImport } from './routes/_app.workflows.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppClaimsRoute = AppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandCenterRoute = AppCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreRoute = AppCoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsRoute = AppEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceRoute = AppGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsRoute = AppSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppSsoRoute = AppSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemetryRoute = AppTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsWorkflowIdRunsRoute =
  AppWorkflowsWorkflowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AppWorkflowsWorkflowIdRoute,
  } as any)
const AppWorkflowsRunsRunIdRoute = AppWorkflowsRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/claims': typeof AppClaimsRoute
  '/command-center': typeof AppCommandCenterRoute
  '/connectors': typeof AppConnectorsRoute
  '/contracts': typeof AppContractsRoute
  '/core': typeof AppCoreRoute
  '/dashboard': typeof AppDashboardRoute
  '/decisions': typeof AppDecisionsRoute
  '/environments': typeof AppEnvironmentsRoute
  '/evidence': typeof AppEvidenceRoute
  '/governance': typeof AppGovernanceRoute
  '/organizations': typeof AppOrganizationsRoute
  '/projects': typeof AppProjectsRoute
  '/secrets': typeof AppSecretsRoute
  '/sso': typeof AppSsoRoute
  '/telemetry': typeof AppTelemetryRoute
  '/users': typeof AppUsersRoute
  '/workflows': typeof AppWorkflowsRouteWithChildren
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/runs': typeof AppWorkflowsWorkflowIdRunsRoute
  '/workflows/runs/$runId': typeof AppWorkflowsRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/claims': typeof AppClaimsRoute
  '/command-center': typeof AppCommandCenterRoute
  '/connectors': typeof AppConnectorsRoute
  '/contracts': typeof AppContractsRoute
  '/core': typeof AppCoreRoute
  '/dashboard': typeof AppDashboardRoute
  '/decisions': typeof AppDecisionsRoute
  '/environments': typeof AppEnvironmentsRoute
  '/evidence': typeof AppEvidenceRoute
  '/governance': typeof AppGovernanceRoute
  '/organizations': typeof AppOrganizationsRoute
  '/projects': typeof AppProjectsRoute
  '/secrets': typeof AppSecretsRoute
  '/sso': typeof AppSsoRoute
  '/telemetry': typeof AppTelemetryRoute
  '/users': typeof AppUsersRoute
  '/workflows': typeof AppWorkflowsRouteWithChildren
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/runs': typeof AppWorkflowsWorkflowIdRunsRoute
  '/workflows/runs/$runId': typeof AppWorkflowsRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/claims': typeof AppClaimsRoute
  '/_app/command-center': typeof AppCommandCenterRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/core': typeof AppCoreRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/decisions': typeof AppDecisionsRoute
  '/_app/environments': typeof AppEnvironmentsRoute
  '/_app/evidence': typeof AppEvidenceRoute
  '/_app/governance': typeof AppGovernanceRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/secrets': typeof AppSecretsRoute
  '/_app/sso': typeof AppSsoRoute
  '/_app/telemetry': typeof AppTelemetryRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/workflows': typeof AppWorkflowsRouteWithChildren
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRouteWithChildren
  '/_app/workflows/$workflowId/runs': typeof AppWorkflowsWorkflowIdRunsRoute
  '/_app/workflows/runs/$runId': typeof AppWorkflowsRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/claims'
    | '/command-center'
    | '/connectors'
    | '/contracts'
    | '/core'
    | '/dashboard'
    | '/decisions'
    | '/environments'
    | '/evidence'
    | '/governance'
    | '/organizations'
    | '/projects'
    | '/secrets'
    | '/sso'
    | '/telemetry'
    | '/users'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/runs'
    | '/workflows/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/claims'
    | '/command-center'
    | '/connectors'
    | '/contracts'
    | '/core'
    | '/dashboard'
    | '/decisions'
    | '/environments'
    | '/evidence'
    | '/governance'
    | '/organizations'
    | '/projects'
    | '/secrets'
    | '/sso'
    | '/telemetry'
    | '/users'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/runs'
    | '/workflows/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/claims'
    | '/_app/command-center'
    | '/_app/connectors'
    | '/_app/contracts'
    | '/_app/core'
    | '/_app/dashboard'
    | '/_app/decisions'
    | '/_app/environments'
    | '/_app/evidence'
    | '/_app/governance'
    | '/_app/organizations'
    | '/_app/projects'
    | '/_app/secrets'
    | '/_app/sso'
    | '/_app/telemetry'
    | '/_app/users'
    | '/_app/workflows'
    | '/_app/workflows/$workflowId'
    | '/_app/workflows/$workflowId/runs'
    | '/_app/workflows/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/claims': {
      id: '/_app/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AppClaimsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command-center': {
      id: '/_app/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AppCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core': {
      id: '/_app/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof AppCoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/environments': {
      id: '/_app/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof AppEnvironmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence': {
      id: '/_app/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance': {
      id: '/_app/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AppGovernanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets': {
      id: '/_app/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AppSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sso': {
      id: '/_app/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof AppSsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telemetry': {
      id: '/_app/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof AppTelemetryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/$workflowId/runs': {
      id: '/_app/workflows/$workflowId/runs'
      path: '/runs'
      fullPath: '/workflows/$workflowId/runs'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AppWorkflowsWorkflowIdRoute
    }
    '/_app/workflows/runs/$runId': {
      id: '/_app/workflows/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflows/runs/$runId'
      preLoaderRoute: typeof AppWorkflowsRunsRunIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
  }
}

interface AppWorkflowsWorkflowIdRouteChildren {
  AppWorkflowsWorkflowIdRunsRoute: typeof AppWorkflowsWorkflowIdRunsRoute
}

const AppWorkflowsWorkflowIdRouteChildren: AppWorkflowsWorkflowIdRouteChildren =
  {
    AppWorkflowsWorkflowIdRunsRoute: AppWorkflowsWorkflowIdRunsRoute,
  }

const AppWorkflowsWorkflowIdRouteWithChildren =
  AppWorkflowsWorkflowIdRoute._addFileChildren(
    AppWorkflowsWorkflowIdRouteChildren,
  )

interface AppWorkflowsRouteChildren {
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRouteWithChildren
  AppWorkflowsRunsRunIdRoute: typeof AppWorkflowsRunsRunIdRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRouteWithChildren,
  AppWorkflowsRunsRunIdRoute: AppWorkflowsRunsRunIdRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppClaimsRoute: typeof AppClaimsRoute
  AppCommandCenterRoute: typeof AppCommandCenterRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppCoreRoute: typeof AppCoreRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppEnvironmentsRoute: typeof AppEnvironmentsRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppGovernanceRoute: typeof AppGovernanceRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSecretsRoute: typeof AppSecretsRoute
  AppSsoRoute: typeof AppSsoRoute
  AppTelemetryRoute: typeof AppTelemetryRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppClaimsRoute: AppClaimsRoute,
  AppCommandCenterRoute: AppCommandCenterRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppContractsRoute: AppContractsRoute,
  AppCoreRoute: AppCoreRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppEnvironmentsRoute: AppEnvironmentsRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppGovernanceRoute: AppGovernanceRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSecretsRoute: AppSecretsRoute,
  AppSsoRoute: AppSsoRoute,
  AppTelemetryRoute: AppTelemetryRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
